---

- name: Update apt cache
  tags: install
  apt:
    update_cache: yes

- name: Install NGINX
  tags: install
  apt:
    name: "nginx={{ nginx_version }}"
  notify: restart nginx

- name: Create web user
  tags: install
  user:
    name: "{{ nginx_user }}"
    state: present

- name: Ensure web root exists
  tags: config
  when: not ansible_check_mode
  file:
    path: "{{ nginx_web_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
    
- name: Deploy nginx.conf from template
  tags: config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx
  
- name: Deploy htpasswd file
  tags: config
  copy:
    content: "{{ htpasswd_content }}"
    dest: /etc/nginx/.htpasswd
    owner: root
    group: "{{ nginx_user }}"
    mode: "0640"
  notify: restart nginx

- name: Deploy index.html with variable
  tags: content
  template:
      src: index.html.j2
      dest: "{{ nginx_web_root }}/index.html"
      owner: "{{ nginx_user }}"
      group: "{{ nginx_user }}"
      mode: "0644"
  notify: restart nginx