---

- name: Update apt cache
  tags: install
  apt:
    update_cache: yes

- name: Install NGINX
  tags: install
  apt:
    name: "nginx={{ nginx_version }}"
  notify: restart nginx

- name: Create web user
  tags: install
  user:
    name: "{{ nginx_user }}"
    state: present

- name: Ensure web root exists
  tags: config
  file:
    path: "{{ nginx_web_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
